-- Esta migration intermediária ficou obsoleta.
-- O conteúdo anterior tentava alterar tabelas que só passam a existir
-- em migrations posteriores, como `FeedbackAnswer`, `IssueReport`
-- e `ReportShareLink`, o que quebrava a aplicação no shadow database.
--
-- Mantida como no-op para preservar o histórico local sem quebrar
-- a cadeia de migrations do Prisma.
