-- Esta migration intermediária ficou obsoleta.
-- O conteúdo anterior repetia alterações em tabelas que ainda não existiam
-- naquele ponto da cadeia, como `FeedbackAnswer`, `IssueReport`
-- e `ReportShareLink`, o que quebrava `migrate dev`, `migrate reset`
-- e qualquer criação do shadow database.
--
-- Mantida como no-op para preservar o histórico local sem quebrar
-- a sequência de migrations.
